@ruby ..\elang.rb call_function.elang %*
@ruby ..\elang.rb escape.elang %*
@ruby ..\elang.rb fn_name.elang %*
@ruby ..\elang.rb compare.elang %*
@ruby ..\elang.rb if1.elang %*
@ruby ..\elang.rb int.elang %*
@ruby ..\elang.rb plus.elang %*
@ruby ..\elang.rb numeric_operations.elang %*
@ruby ..\elang.rb puts.elang %*
@ruby ..\elang.rb object.elang %*
@ruby ..\elang.rb person.elang %*
@ruby ..\elang.rb initialize.elang %*
@ruby ..\elang.rb string.elang %*
@ruby ..\elang.rb array1.elang %*
@ruby ..\elang.rb array2.elang %*
@ruby ..\elang.rb loop.elang %*
@ruby ..\elang.rb while.elang %*
